### ISSUE TITLE
Breadcrumbs in non generic class view

### ISSUE THREAD

**Issue by fbzyx** [tj-django/django-view-breadcrumbs#153]
Hello,
Is it possible to use this package with other class based views than listview, createview, updateview and deleteview?
I'm using django-tables2 and have had some problems trying to generate breadcrumbs in a SingleTableView.

I see that for each generic class view there is a specific breadcrumbs class.

How can I make it work with a non-generic django class view?

Thank You in advance.

**Comment by jackton1** [comment]
Yes it should be possible to use SingleTableView. I'll update the README to reflect how it can be implemented.
