### ISSUE TITLE
i18n/l10n support

### ISSUE THREAD

**Issue by Crazor** [tj-django/django-view-breadcrumbs#188]
When I add `verbose_name` and `verbose_name_plural` to a model's Meta, the breadcrumbs are as expected. However, even though I use gettext_lazy, the breadcrumbs are never translated and instead show the (english) untranslated string. Everything else in my application is translating correctly.

**Comment by jackton1** [comment]
Can you add a sample configuration ??

**Comment by jackton1** [comment]
@Crazor This has been resolved Thanks
