### ISSUE TITLE
Breadcrumbs for custom views

### ISSUE THREAD

**Issue by blasferna** [tj-django/django-view-breadcrumbs#276]
I have the next view:
```python
CompanyHistory(View):
    template_name = "history.html"
...
```
Url definition
```python
...
path("company/<int:pk>/history/", CompanyHistory.as_view(), name="company_history"),
...
```

According to the documentation, it only supports the following actions:
![image](https://user-images.githubusercontent.com/8385910/114411279-065cea00-9b7a-11eb-8a88-e684c50a0a47.png)

Is there a way to include a custom action?

**Comment by jackton1** [comment]
I'll need to clarify that on the docs but for custom view you can inherit from the `BaseBreadcrumbMixin ` see https://github.com/tj-django/django-view-breadcrumbs#custom-crumbs-home--my-test-breadcrumb

Sample
```py
class CompanyHistory(BaseBreadcrumbMixin, View):
    template_name = "history.html"
    
    def crumbs(self):
        return [...]
```

or 

```py
class CompanyHistory(BaseBreadcrumbMixin, View):
    template_name = "history.html"
    crumbs = [...]
```
