### ISSUE TITLE
 Custom app_label for view using another app's model

### ISSUE THREAD

**Issue by blasferna** [tj-django/django-view-breadcrumbs#368]
I have some views using model from another app, when the view is executed raise an exception `NoReverseMatch ` because `django-view-bradcrumbs` asume the app of the view is in the model app.

I think it can be fixed by adding a new attribute in the class `BaseBreadcrumbMixin`.

```python
class BaseBreadcrumbMixin(object):
    ...
    app_name = None #custom app name
```

Also modify the function `action_view_name`  to adding a new parameter called `app_name`.

```python
def action_view_name(model, action, full=True, app_name=None):
    if app_name:
        app_label = app_name
        model_name = get_model_name(model)
    else:
        app_label, model_name = get_app_name(model)
```
And then modify the mixins:

```python
class ListBreadcrumbMixin(BaseModelBreadcrumbMixin):
    # Home / object List

    @classproperty
    def list_view_name(self):
        return action_view_name(self.model, self.list_view_suffix, full=False, app_name=self.app_name)

...
```

With all that I could use with my view that uses a foreign model

```python
class TestListsView(ListBreadcrumbMixin, ListView):
    app_name = 'foreignapp'
    model = ForeignModel
    template_name = "demo/test-list.html"
```

If there is another way to achieve this I would like to know. Thanks for the project.

**Comment by blasferna** [comment]
Another solution I can think of is to get the application name directly from the request using `request.resolver_match.app_name`

**Comment by jackton1** [comment]
@blasferna This should be available in the latest release. Thanks

**Comment by blasferna** [comment]
@jackton1 Thank you very much for the update, it works great.
