### ISSUE TITLE
Attempting to add breadcrumbs to listview that is related to a detail view via a foreign key

### ISSUE THREAD

**Issue by macumhail** [tj-django/django-view-breadcrumbs#526]
I have been able to get breadcrumbs to work that displays a trail like:
home/projects/project1. However, I can't figure out how to display breadcrumbs on a notes list page of notes related to project1. 

I have a list view "ProjectNotesList" that displays notes on specific projects. Notes are related to projects via a foreign key. When "ListBreadcrumbMixin" is added to the ProjectNotesList view I get the following error:

```py
NoReverseMatch at /projects/project/1/notes/
Reverse for 'projectnotes_list' with no arguments not found. 1 pattern(s) tried: ['projects/project/(?P<pk>[0-9]+)/notes/\\Z']
Request Method: GET
Request URL:    http://co1.localhost:8000/projects/project/1/notes/
Django Version: 3.1.14
Exception Type: NoReverseMatch
Exception Value:    
Reverse for 'projectnotes_list' with no arguments not found. 1 pattern(s) tried: ['projects/project/(?P<pk>[0-9]+)/notes/\\Z']
Exception Location: /Users/user/.local/share/virtualenvs/osite-wGphEfbP/lib/python3.9/site-packages/django/urls/resolvers.py, line 689, in _reverse_with_prefix
Python Executable:  /Users/user/.local/share/virtualenvs/osite-wGphEfbP/bin/python
Python Version: 3.9.6
Python Path:    
['/Users/user/Desktop/otools',
 '/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',
 '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
 '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',
 '/Users/user/.local/share/virtualenvs/osite-wGphEfbP/lib/python3.9/site-packages']
Server time:    Sun, 20 Feb 2022 15:52:17 +0000
```
 
My view:

```py
class ProjectNotesList(ListBreadcrumbMixin,ListView):
    model = ProjectNotes
    template_name = 'company_accounts/project_notes.html'
    comments = ProjectNotes.comments


    def related_project(self, **kwargs):
        project = get_object_or_404(Project, id=self.kwargs.get('pk'))
        notes = ProjectNotes.objects.all
        return notes

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        context['project'] = get_object_or_404(Project, id=self.kwargs.get('pk'))
        return context



    commentscount = ProjectNotes.objects.annotate(num_comments=Count('comments'))
```
    
My URL:
```py
path('project/<int:pk>/notes/', ProjectNotesList.as_view(), name='projectnotes_list'),
```

Is it possible to get this to work with this configuration?

**Comment by macumhail** [comment]
It looks like this probably isn't possible.

**Comment by jackton1** [comment]
@macumhail There are a couple of things wrong with your code above

1. Using class level attributes to access model properties is a bad practice
2. `commentscount` seems to be dangling and would likely need to be used inside the corresponding method.
3.  `notes = ProjectNotes.objects.all` should be `notes = ProjectNotes.objects.all()`
4. Also your trying to visit  URL `/projects/project/1/notes/` but your URL configuration is `project/1/notes/`

**Comment by macumhail** [comment]
Thank you for the suggestions, Jackton. I will make these changes. I am a new to Django - still a lot to learn.

**Comment by macumhail** [comment]
Jackton, I am still not able to get this to work (no doubt due to being new to Django). If I change my url configuration to projects/project/1/notes (instead of project/1/notes/) for the notes list, the resulting URL when I click on the link is projects/projects/project/1/notes.
